# Generated by Django 4.2.2 on 2023-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_api', '0002_weather_check_icon_weather_check_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_check',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
