# Generated by Django 4.2.2 on 2023-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_api', '0003_alter_weather_check_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_check',
            name='temperature',
            field=models.FloatField(default=None, null=True),
        ),
    ]
